export const PERMISSIONS = Object.freeze({
  DASHBOARD_OVERVIEW: 'DASHBOARD_OVERVIEW',
  DASHBOARD_REVENUE_TREND: 'DASHBOARD_REVENUE_TREND',
  DASHBOARD_TOP_PRODUCTS: 'DASHBOARD_TOP_PRODUCTS',
  DASHBOARD_OCCUPANCY: 'DASHBOARD_OCCUPANCY',
  DASHBOARD_ACTIVE_ORDERS: 'DASHBOARD_ACTIVE_ORDERS',
  MENU_CATEGORY_MANAGE: 'MENU_CATEGORY_MANAGE',
  MENU_ITEM_MANAGE: 'MENU_ITEM_MANAGE',
  MENU_VARIANT_MANAGE: 'MENU_VARIANT_MANAGE',
  MENU_MODIFIER_MANAGE: 'MENU_MODIFIER_MANAGE',
  MENU_BUNDLE_MANAGE: 'MENU_BUNDLE_MANAGE',
  ORDER_MONITOR: 'ORDER_MONITOR',
  ORDER_HISTORY_VIEW: 'ORDER_HISTORY_VIEW',
  ORDER_CANCEL: 'ORDER_CANCEL',
  INVENTORY_MASTER_MANAGE: 'INVENTORY_MASTER_MANAGE',
  INVENTORY_PURCHASE_MANAGE: 'INVENTORY_PURCHASE_MANAGE',
  INVENTORY_STOCK_OPNAME: 'INVENTORY_STOCK_OPNAME',
  INVENTORY_REPORT_VIEW: 'INVENTORY_REPORT_VIEW',
  FINANCE_REPORT_VIEW: 'FINANCE_REPORT_VIEW',
  FINANCE_EXPORT_PDF: 'FINANCE_EXPORT_PDF',
  SHIFT_RECAP_VIEW: 'SHIFT_RECAP_VIEW',
  EMPLOYEE_MANAGE: 'EMPLOYEE_MANAGE',
  EMPLOYEE_SHIFT_MANAGE: 'EMPLOYEE_SHIFT_MANAGE',
  AUDIT_LOG_VIEW: 'AUDIT_LOG_VIEW',
  PROMO_MANAGE: 'PROMO_MANAGE',
  SYSTEM_SETTINGS_MANAGE: 'SYSTEM_SETTINGS_MANAGE',
  SYSTEM_BACKUP_MANAGE: 'SYSTEM_BACKUP_MANAGE',
})

export const DASHBOARD_PERMISSIONS = [
  PERMISSIONS.DASHBOARD_OVERVIEW,
  PERMISSIONS.DASHBOARD_REVENUE_TREND,
  PERMISSIONS.DASHBOARD_TOP_PRODUCTS,
  PERMISSIONS.DASHBOARD_OCCUPANCY,
  PERMISSIONS.DASHBOARD_ACTIVE_ORDERS,
]

export const MENU_PERMISSIONS = [
  PERMISSIONS.MENU_CATEGORY_MANAGE,
  PERMISSIONS.MENU_ITEM_MANAGE,
  PERMISSIONS.MENU_VARIANT_MANAGE,
  PERMISSIONS.MENU_MODIFIER_MANAGE,
  PERMISSIONS.MENU_BUNDLE_MANAGE,
]

export const MENU_ADVANCED_PERMISSIONS = [
  PERMISSIONS.MENU_MODIFIER_MANAGE,
  PERMISSIONS.MENU_BUNDLE_MANAGE,
]

export const COSTING_PERMISSIONS = [
  PERMISSIONS.MENU_ITEM_MANAGE,
  PERMISSIONS.INVENTORY_MASTER_MANAGE,
  PERMISSIONS.INVENTORY_REPORT_VIEW,
]

export const ORDER_PERMISSIONS = [
  PERMISSIONS.ORDER_MONITOR,
  PERMISSIONS.ORDER_HISTORY_VIEW,
]

export const SYSTEM_SETTINGS_PERMISSIONS = [
  PERMISSIONS.SYSTEM_SETTINGS_MANAGE,
  PERMISSIONS.SYSTEM_BACKUP_MANAGE,
]
